### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by keralab** [nolanslade/zp18#19]
Due December 5th

"Your poster will be evaluated by the instructor or TA, and you will have to stage an additional guerilla poster presentation and collect 20 tweets from passers-by showing they understand your project (at the appropriate passer-by level) and think it is cool."

"Does your poster explain what you are doing and why you are doing it?  Will a random Mac student tweet that what you are doing is great (fail) or will they they tweet a reason why what you are doing is important and why your technical insight makes them believe you can succeed."

@AaskaS

**Comment by keralab** [comment]
Working on draft of poster to share with @JacquesCarette and Dr Anand by tomorrow morning so that we can receive feedback ahead of printing it on Monday (Dec 3rd)

**Comment by JacquesCarette** [comment]
:+1:

**Comment by keralab** [comment]
In progress poster committed: https://github.com/nolanslade/zp18/commit/da996845e7c4d890ba60eb478a94ba5f90756823
Using Cognitive Load poster (provided by Dr Anand) as a template.

#### TODO:
- [ ] Add images
- [ ] Add references
- [ ] Add authors
- [ ] Reformat
- [ ] Review all writing

**Comment by keralab** [comment]
Addressing @JacquesCarette and Dr Thomas's reviews https://github.com/nolanslade/zp18/commit/735f08a2a4060f87e7e6117324be7de0a7595f66
Starting new version after receiving Dr Anand's reviews (trying out Powerpoint) https://github.com/nolanslade/zp18/commit/103257a6004e8efd81926c09b8ec4eee5a604785
