### ISSUE TITLE
Metrics: Data Classification / CSV/SQL Schemas

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#26]
We need to decide what metrics we are capturing and in what granularity.

Ideas:
- Simulation state: User name/id, Simulation #, Day #, Day time total, day time elapsed, points earned...., impairments, impairment level ...
- User state: Headset position, current task (walking or carrying?) ....

Simulation One: ??

Global Time
Day
State
Day Running Time
Total Score
Day Score
Current (Water) Carry Amount
Headset X (Normalize to 0,Y,0 being a corner?)
Headset Y
Headset Z (Normalize to 0,Y,0 being a corner?)
Impairment 1 Factor (Initial)
Impairment 1 Factor (Current)
... other impairments
..... ?

These will also influence our output CSV formats at the end of each experiment / SQL DB schemas.

**Comment by JacquesCarette** [comment]
You should try to understand what Stephanie et al are trying to obtain (as results), and then reverse engineer what data would be most helpful towards that task. Being systematic about that might cause you to discover some very simple additional data to track that makes a big difference in the results.

**Comment by nolanslade** [comment]
We have a good base for our schema, attached.

[Uploading sample_CSV_v1_7.xlsx…]()
