### ISSUE TITLE
Unity Testing: Sound for HTC Vive Headset

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#30]

**Comment by JacquesCarette** [comment]
Note that Unity has a built-in unit testing framework now. So it is possible to automate quite a lot of the testing, which saves time in the long run. The 4GP6 students are using it for their game, so you can get some advice from them if you need it.

**Comment by nolanslade** [comment]
Done, implemented key sound effects here: 
https://github.com/nolanslade/zp18/commit/cd44730be210a4b6b835a2072ee1012ae9f950aa
https://github.com/nolanslade/zp18/commit/e0284b55ab561cba611e2e037f36994a6dffd464
https://github.com/nolanslade/zp18/commit/e8ad3fd2fd6fd215ac8ce5f8da285d5c77c32d5c
