### ISSUE TITLE
Simulation One: HUD and Overlays

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#36]
Things we'll need:

- [x] HUD: Current Day # and Total Days, Time remaining for current day, Impairment level / 'health' level, Reward payout per day/total
- [x] Transition Countdown/State
- [ ] Error State - not pressing or required
- [x] Pause State

We have a couple options. We could have a HUD, or, we could display this information on a display inside the room somehow. Maybe incorporate a television into the environment and display it on there? (decided on HUD but cool idea, maybe incorporate later or something?)

**Comment by keralab** [comment]
- HUD is located above the source and sink
- Pause overlay is transparent blue attached to the camera, making the scene appear different - red was too disorientating.
- Transition overlay is text attached to the camera, so it floats in the user's center field of vision

**Comment by keralab** [comment]
All but error state is complete.
This can be added later as there are more pressing issues.
