### ISSUE TITLE
Simulation One: Fix Collision Behaviour with Water, Surfaces & Container

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#37]
Currently, the container prefabs we've added to the scene can carry water XOR react properly to gravity + not fall through the floor. We'll need to change that to an inclusive or if we're to make a functional simulation.

**Comment by nolanslade** [comment]
Vyome knows how to work around this using custom colliders.

**Comment by JacquesCarette** [comment]
Note that it is not "good process" to close an issue just when someone knows how to solve it. The best method is to close it with a commit number, where the fix has actually been implemented.
