### ISSUE TITLE
Simulation One: Impairments

### ISSUE THREAD

**Issue by keralab** [nolanslade/zp18#40]
Create all necessary impairments
- [ ] Physical Speed Penalty
- [ ] Visual Fog
- [x] Physical Tremor
- [ ] Physical Dexterity/Gravity
- [ ] Physical Delayed Action

**Comment by nolanslade** [comment]
Ground work for fog and gravity:
https://github.com/nolanslade/zp18/commit/68dc8402d568469b48421585c36f12c5bc094eeb
and
https://github.com/nolanslade/zp18/commit/d9ed4f99eb26702de5272d155813e2687b191623
and
https://github.com/nolanslade/zp18/commit/10706a8819b9608b81f4d8751de2eeb55a251fac

**Comment by nolanslade** [comment]
Closing - added issues for each one.
