### ISSUE TITLE
Simulation One: Persistance - Text File

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#43]
We should always output CSV formatted output to a text file for each simulation.

Each file should be timestamped, have necessary general info, as well as timestamped CSV entries with simulation data (every second?).

**Comment by nolanslade** [comment]
Updated method signatures + added a flag on SimManager. Some fields not functional, left comments. 
https://github.com/nolanslade/zp18/commit/082fbb47ae3f5412737d5270a834e34ebc036f30

**Comment by keralab** [comment]
Added a stream writer to print data to a file using a relative path (data file).
Not tested yet.
https://github.com/nolanslade/zp18/commit/9e491eaca944c6c61fd60179b3f2862f0c4bdeef

**Comment by keralab** [comment]
Some fields need to be implemented but persistence to csv works.
