### ISSUE TITLE
Simulation One: Paying / Waiting for Treatment

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#47]
Treatment.cs has a method to calculate the current cost of treatment. Next, we'll need to create a first aid station on one side of the room where the participant can walk to and pay for their treatment, should they choose to.

- [x] Create desk with pill bottles in environment
- [x] Create UIs that display the wait time / cost for their respective pill bottle
- [x] Add colliders and pick-up ability for the pill bottles
- [x] Pay: Full health returns upon choosing paying option, money decreases applicable amount
- [x] Pay: if the treatment isn't affordable, reset pill bottle so they can try again later
- [x] Wait: Pedestal for bucket; move the bucket there once bottle is grabbed
- [x] Wait: lock bucket to the pedestal for the total duration of the wait time, then return to full health

**Comment by keralab** [comment]
Currently we have implement the desk with 2 pill bottles, each located on a pedestal and with a respective UI. The blue pedestal and UI is for the waiting option, the red pedestal and UI for the paying option. The UI for waiting (Blue) displays the amount of time the participant will have to wait for free treatment (in pause mode). The UI for paying (Red) displays the cost of immediate treatment.

**Comment by nolanslade** [comment]
Put methods in for pill manager and sim manager for the pay option here: https://github.com/nolanslade/zp18/commit/ac7fb75feae893c1ddca29edc275c1bde780d902

The hand script, when picking up a bottle, will just need to call PillManager.attemptObtain() with the appropriate type.

**Comment by nolanslade** [comment]
Pay treatment works, but there's an issue with how I'm trying to reset the pill if they can't afford it: https://github.com/nolanslade/zp18/commit/79f020c193e0cd02d31005cee8861f624f9a905d

**Comment by nolanslade** [comment]
All done, pay and wait now 100% working: 
https://github.com/nolanslade/zp18/commit/bea971bbe4ca45686329322ff3a1f3d29afe4b71
https://github.com/nolanslade/zp18/commit/cfcc7f838752acb69a81864092e9d544d420869f
https://github.com/nolanslade/zp18/commit/bb18fd87fde03789dcc3531c9a6be027dd0bd171
https://github.com/nolanslade/zp18/commit/4f12b52054afa8021dd372e3956d6c02108e8f23
https://github.com/nolanslade/zp18/commit/3268e7fe13e232e930373dc1c2aef83695d0a63b
https://github.com/nolanslade/zp18/commit/76b94f287da93fb7e0d51f687b12f17086bd33ba
https://github.com/nolanslade/zp18/commit/4b38db799870a27e3983ac32f4d365f0d11380c4
https://github.com/nolanslade/zp18/commit/a0376a985896c9d2644dcab546f96166bebc881c
https://github.com/nolanslade/zp18/commit/ae664f5c5713206befa47cfd7d04dad8df8cad4a
https://github.com/nolanslade/zp18/commit/d9793d466ed6fe18600a11892121532f13866c8f
https://github.com/nolanslade/zp18/commit/8de7a36916196af6978374dae489a9bbed69d945
https://github.com/nolanslade/zp18/commit/c86a7afd6318fc8f90c0afa80b968d30fda4c81e
