### ISSUE TITLE
Simulation One: Persistence  - Missing Fields

### ISSUE THREAD

**Issue by keralab** [nolanslade/zp18#73]
There are fields that are currently not being measured or not added as a field for persistence

- [x] Speed (being measured, not being persisted)
- [x] Headset position (being measured, not being persisted)
- [x] Headset angle (not being measured or persisted)
- [x] Need full introduction with user / simulation info

**Comment by nolanslade** [comment]
Done here: https://github.com/nolanslade/zp18/commit/d82ab4d38d6d2f854dac45e72dc7930f7c779d99
