### ISSUE TITLE
Full Simulation: Sound Effect for Scoring/Pouring in Destination

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#83]
We essentially have sound effects for everything else- would be nice to have this one too. Might need to be careful on how we implement it to avoid spamming.

Would probably be best to use the Water Audio source, because we know it's impossible to score and fill the bucket at the same time.

**Comment by keralab** [comment]
Implemented with generic water sound - need to add new drain sound clip

**Comment by nolanslade** [comment]
Implementation done: https://github.com/nolanslade/zp18/commit/3f7a5974dcebfa4de4a61e58a0a928904621658b
