### ISSUE TITLE
Config Parsing: Incorrect Default Values For Treatments

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#86]
For function 
C(c-bT+(aT)^2)

We should be using defaults:
c = day length
b = 2
a = 1 / day length

**Comment by AaskaS** [comment]
The commit [https://github.com/nolanslade/zp18/commit/860e76b0c80e3449947161641f12ac2ce84c8d4d](url) mistakenly has a = 1 / dayCount but that has been fixed now
