### ISSUE TITLE
Full Simulation: Impairment - Fog

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#92]
I put some groundwork in already, but basically we'll want to hinder their ability to see in whatever way works best. 

- Have a maximum opacity
- Set opacity = str * max opacity

We'll need to unapply it when giving instructions, or at least make the instructions readable somehow.

**Comment by keralab** [comment]
Currently fog works where 0% impairment strength is actually 75% opacity and 100% impairment strength is 95% opacity.
Need to turn off during limbo mode to show instructions.

**Comment by keralab** [comment]
Fog is turned off during limbo mode so that instructions can be seen and the participant can learn the location of the treatment station.
https://github.com/nolanslade/zp18/commit/8cae158735cb54578c421b84d61f8ed2f99d0367
