### ISSUE TITLE
Full Simulation: Implement Modify Impairment Factors Method

### ISSUE THREAD

**Issue by nolanslade** [nolanslade/zp18#98]
In SimManager:

private void modifyImpairmentFactors (float factor)

Needs to be implemented so that we can use partially effective treatments, i.e. a treatment that only takes away half (0.5 * current str) of the impairment. For each active impairment, we'll need to modify the strength by taking the current strength, and then subtracting factor * current strength from it.

One way is to unapply them all, recalculate strength, and then reapply them.

**Comment by keralab** [comment]
This now works for all implemented impairments (shake, fog and speed penalty)
https://github.com/nolanslade/zp18/commit/74a8c6c9139b3d4a625f0a24c6b5dba291c4c93c

**Comment by keralab** [comment]
This now works for all implemented impairments (shake, fog and speed penalty)
https://github.com/nolanslade/zp18/commit/74a8c6c9139b3d4a625f0a24c6b5dba291c4c93c
